### ISSUE TITLE
Get A Blank Screen

### ISSUE THREAD

**Issue by adiatmad** [mapswipe/mapswipe-web#14]
**Describe the bug**
I got the blank (white) screen 

**To Reproduce**
1. Swipe some tiles
2. And mine screen just disappeared, all white
3. Refresh the browser
4. Everything is OK

**Expected behavior**
I expect can continue to swipe without any interuption

**Screenshots**
Here is the screenshot
![image (3)](https://github.com/mapswipe/mapswipe-web/assets/38268616/5c14f09c-58f6-42a4-be4a-b081fb86f653)

**Desktop (please complete the following information):**
 - OS:Windows 11
 - Browser Firefox 126.0 (64-bit)

**Comment by nicolelaine** [comment]
Hi, I'm also having this issue. 

*Describe the bug*
While clicking the > arrow at the bottom of the screen and looking through the tiles, my screen suddenly turned white. I was not clicking at the time. I actually recorded this, as I was making a tutorial at the time, so can send this over as well. 

*To Reproduce*
1.) Choose a project on MS4Web. In my case, I chose this one: https://web.mapswipe.org/#/en/projects/-NwG8EbUqZW7t0R8TxKq
2.) Click the > to advance to further columns
3.) Suddenly the screen goes white.
4.) Refreshing does seem to bring the screen back, but it sometimes takes some time.

*Expected behavior*
I would expect that I can continuing clicking through without the webapp crashing.

*Screenshots*
Ack, I forgot to grab it before I refreshed, but it looks exactly as above.

*Desktop (please complete the following information)*
M1 mac 
Ventura 13.2.1
Chrome 124.0.6367.158 (Official Build) (arm64)

**Comment by Pseudorandom-Pseudonym** [comment]
Here are some points that may help identify and address this malfunction;

- The only action necessary to trigger the white screen is clicking "select" on a project. The white screen error can occur while still looking at the "How to Contribute?" pop-up i.e. having not interacted with the task in any way, no other input what so ever. 
- There is certainly variance in the time period after a task is selected untill a white screen error occurs. I have not measured this, but I think that this time period has a negative correlation with the amount of interaction a user has with a task, and a positive correlation with the amount of time a user waits before refreshing the page.
- I have only encountered this malfunction when working a task in a "find" type project. I have never encountered it while working on a task within a "validate" type project.

I will also make an ammendment to the previous comments in this thread. Reloading puts you into a different task than the one you were just working on. Work on a task appears to be lost given the lack of saving; I was served a task I previously worked on (and marked) with no marked squares.

**Comment by xplora1a** [comment]
I would add that this only seems to happen on the Identify Buildings tasks
