### ISSUE TITLE
"Continue Mapping" button never activates after finishing project of type Validate with custom options

### ISSUE THREAD

**Issue by ofr1tz** [mapswipe/mapswipe-web#18]
**Describe the bug**
Currently, Firebase discards all results for projects of type Validate with custom options from the web app, as the results do not contain an entry for appVersion. [Firebase discards all results without appVersion](https://github.com/mapswipe/python-mapswipe-workers/blob/9cc1914008832d44ebbbabbd6b67990f830b3104/firebase/functions/src/index.ts#L58C1-L78C6), as earlier versions of the *mobile* app (that do not write appVersion) are not able to handle custom options properly.

**To Reproduce**
1. Choose a project of type Validate with custom options
2. Complete the task group and click the save button
3. The "Continue Mapping" button will not activate, because the user's project contributions are never updated as the results are discarded

**Expected behavior**
Results for projects of type validate with custom options should be accepted and correctly processed by Firebase. This could be achieved by:

a) adapting the respective Firebase function,
b) adapting the web app to include appVersion with the submitted result. In this case, the appVersion should either carry an informative suffix or the result should include an additional property to indicate which client the version number refers to.

**Comment by Pseudorandom-Pseudonym** [comment]
@ofr1tz could you please change the title of this issue to something resembling 'Unable to Click Continue Mapping After Finishing a Task on a Validate Type Project' to reduce the number of duplicate issues, and to better track them. 

I know you're using it as a note to self, but I wrote a bug report when I came accross this same issue, because I couldn't tell it was the same one based on the title. 

I'll just post it here in case it's of any use.

**Comment by Pseudorandom-Pseudonym** [comment]
**Describe the bug**
After finishing and clicking save on a task; the 'well done mapper!' pop-up appears. Only the 'see all projects button is clickable while the continue mapping button is not. It buffers endlessly, but never loads (even though the web page is loaded). 

**To Reproduce**
Steps to reproduce the behavior:
1. Search for projects
2. Click on contribute to a Validation Project
3. Finish the task and save your contribution
4. See error

**Expected behavior**
The Pop-up appears, and I can continue to contribute by clicking on 'continue mapping'

**Screenshots**
![Mapswipe4web Endlessly Buffering Continue Mapping Button](https://github.com/mapswipe/mapswipe-web/assets/170571789/88a8727e-f541-40ff-9a8b-5a1266e50d50)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Firefox]
 - Version [126.0.1]

**Additional context**
This bug forces contributors to got back through the projects page, find the same project, and click contribute to it. From my experience this bug is **not** random in nature: it occurs everytime, without fail. It appears by the message on the bottom of the screen that contributions are thankfully saved.
[It appears by your bug report that this, may in fact, not be the case:)]

**Comment by Pseudorandom-Pseudonym** [comment]
Thank you!
