### ISSUE TITLE
Enhancement: a way to showcase project urgency / priority

### ISSUE THREAD

**Issue by nicolelaine** [mapswipe/mapswipe-web#29]
**Is your feature request related to a problem? Please describe.**
Add a way to showcase the urgency of the project 

**Describe the solution you'd like**
A clear panel that showcases the urgency. Like how you can see on the TM in this screenshot:
<img width="1418" alt="Screenshot 2024-07-11 at 15 32 12" src="https://github.com/mapswipe/mapswipe-web/assets/15011784/734703c5-a76b-46ce-a1ce-3f52171ebb9f">

**Describe alternatives you've considered**
Could put this in the title of the project for now.

**Comment by ofr1tz** [comment]
To my knowledge, we do not capture any info on the urgency of the MapSwipe project at the moment. For enabling MapSwipe web to showcasing the project urgency, we would need changes in the back end (or rather: the Manager Dashboard, probably) so that an urgency attribute is written to the project in Firebase. I guess the discussion could best be started with an [issue on the python mapswipe workers repo](https://github.com/mapswipe/python-mapswipe-workers/issues).

I am not fully aware, though, how urgency works in the TM: Is urgency declared at the moment of project creation by the person creating the project? Does urgency change over time?

**Comment by nicolelaine** [comment]
You are correct that there is not currently a way to list urgency on MapSwipe (also on the mobile version.)

On the Tasking Manger, there is a section in the Manager Dashboard to set the urgency. So one can set it upon creation and publication of the project, but then it's also easily to update at any point. And it does often get updated over the course of the project. 

It looks like this: 
![Screenshot 2024-07-16 at 15 46 53](https://github.com/user-attachments/assets/6d1c050d-eca9-4aad-aaa2-6ac4c918c8ea)

**Comment by ofr1tz** [comment]
Thanks for the info!

I'll close the issue here as this requires discussion for the entire MapSwipe eco-system (here: https://github.com/mapswipe/python-mapswipe-workers/issues/952)
